// <auto-generated />
namespace PhamHoaiNam_2011068871.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userinitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userinitial));
        
        string IMigrationMetadata.Id
        {
            get { return "202303040134352_user initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
